### ISSUE TITLE
”预约入校时间“无法编辑问题

### ISSUE THREAD

**Issue by Alex-SYZ1** [huajibing/PKUVisitorHelper#1]
您的代码很有参考价值，感谢！好奇这些js知识在哪里学比较方便

另外发现一个小bug，”预约入校时间“使用您的插件自动填写后，下拉框无法手动点击出现，因而也无法在插件输入内容后再手动修改入校时间。（如下的视频所示）

https://github.com/user-attachments/assets/a7253bc1-0fe9-422c-89a3-6e09150f5b8c

**Comment by huajibing** [comment]
你好！JS其实很容易上手，我的建议是了解一些基本语法之后，一边写一边学，有问题也可以询问GPT。
btw，感谢你提出的bug，这个问题可能是页面加载不充分导致。由于对前端框架渲染的页面进行DOM操作实在复杂，我采取了折中的方案，添加了一个0.6秒的延时，目前这个问题至少在我的浏览器上已经得到解决。
望知悉！
